### ISSUE TITLE
The fact that the opportunistic contest step doesn’t feel optional is confusing

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/arlo#1763] opened 2022-12-24 21:54 UTC
The fact that the opportunistic contest step doesn’t feel optional is confusing.

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/C01F2CH62TS/p1667427361395059

**Comment by umbernhard** [comment] 2023-03-01 20:21
Duplicate of https://github.com/votingworks/arlo/issues/1537

**Closed by umbernhard** 2023-03-01 20:21 UTC
Labels: triage
